---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: fedora-23
  - name: fedora-24
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2

suites:
  - name: default
    data_bags_path: 'test/integration/default/data_bags'
    encrypted_data_bag_secret_key_path: 'test/integration/default/encrypted_data_bag_secret'
    run_list:
      - recipe[munge::default]
    attributes:
